add docker in test

diff --git a/config/v2ray b/config/v2ray
--- a/config/v2ray
+++ b/config/v2ray
@@ -1,13 +1,4 @@
 #!/bin/sh
-#
-# v2ray        Startup script for v2ray
-#
-# chkconfig: - 24 76
-# processname: v2ray
-# pidfile: /var/run/v2ray.pid
-# description: V2Ray proxy services
-#
-
 ### BEGIN INIT INFO
 # Provides:          v2ray
 # Required-Start:    $network $local_fs $remote_fs
@@ -18,13 +9,13 @@
 # Description:       V2Ray proxy services
 ### END INIT INFO
 
+# Acknowledgements: Isulew Li <netcookies@gmail.com>
+
 DESC=v2ray
 NAME=v2ray
 DAEMON=/usr/bin/v2ray/v2ray
 PIDFILE=/var/run/$NAME.pid
-LOCKFILE=/var/lock/subsys/$NAME
 SCRIPTNAME=/etc/init.d/$NAME
-RETVAL=0
 
 DAEMON_OPTS="-config /etc/v2ray/config.json"
 
@@ -34,84 +25,126 @@ DAEMON_OPTS="-config /etc/v2ray/config.json"
 # Read configuration variable file if it is present
 [ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
 
-start() {
-  local pids=$(pgrep -f $DAEMON)
-  if [ -n "$pids" ]; then
-    echo "$NAME (pid $pids) is already running"
-    RETVAL=0
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
+. /lib/lsb/init-functions
+
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    mkdir -p /var/log/v2ray
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    #   3 if configuration file not ready for daemon
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --background -m -- $DAEMON_OPTS \
+        || return 2
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
+    RETVAL="$?"
+    [ "$RETVAL" = 2 ] && return 2
+    # Wait for children to finish too if this is a daemon that forks
+    # and if the daemon is only ever run from this initscript.
+    # If the above conditions are not satisfied then add some other code
+    # that waits for the process to drop all resources that could be
+    # needed by services started subsequently.  A last resort is to
+    # sleep for some time.
+    start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
+    [ "$?" = 2 ] && return 2
+    # Many daemons don't delete their pidfiles when they exit.
+    rm -f $PIDFILE
+    return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
     return 0
-  fi
-
-  echo -n $"Starting $NAME: "
-
-  mkdir -p /var/log/v2ray
-  $DAEMON $DAEMON_OPTS 1>/dev/null 2>&1 &
-  echo $! > $PIDFILE
-
-  sleep 2
-  pgrep -f $DAEMON >/dev/null 2>&1
-  RETVAL=$?
-  if [ $RETVAL -eq 0 ]; then
-    success; echo
-    touch $LOCKFILE
-  else
-    failure; echo
-  fi
-  return $RETVAL
 }
 
-stop() {
-  local pids=$(pgrep -f $DAEMON)
-  if [ -z "$pids" ]; then
-    echo "$NAME is not running"
-    RETVAL=0
-    return 0
-  fi
-
-  echo -n $"Stopping $NAME: "
-  killproc -p ${PIDFILE} ${NAME}
-  RETVAL=$?
-  echo
-  [ $RETVAL = 0 ] && rm -f ${LOCKFILE} ${PIDFILE}
-}
-
-reload() {
-  echo -n $"Reloading $NAME: "
-  killproc -p ${PIDFILE} ${NAME} -HUP
-  RETVAL=$?
-  echo
-}
-
-rh_status() {
-  status -p ${PIDFILE} ${DAEMON}
-}
-
-# See how we were called.
 case "$1" in
   start)
-    rh_status >/dev/null 2>&1 && exit 0
-    start
-    ;;
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
+  ;;
   stop)
-    stop
+    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    do_stop
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
   status)
-    rh_status
-    RETVAL=$?
+       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       ;;
+  reload|force-reload)
+    #
+    # If do_reload() is not implemented then leave this commented out
+    # and leave 'force-reload' as an alias for 'restart'.
+    #
+    log_daemon_msg "Reloading $DESC" "$NAME"
+    do_reload
+    log_end_msg $?
     ;;
-  restart)
-    stop
-    start
+  restart|force-reload)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
     ;;
-  reload)
-    reload
-  ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|reload|restart}" >&2
-    RETVAL=2
-  ;;
+    #echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
+    echo "Usage: $SCRIPTNAME {start|stop|status|reload|restart|force-reload}" >&2
+    exit 3
+    ;;
 esac
-exit $RETVAL
